services:
  prwrapper:
    build:
      context: .
      dockerfile: ./apps/prwrapper/docker/dev.Dockerfile
      target: development
    ports:
      - '3100:3100'
    volumes:
      - .:/app
    env_file:
      - ./apps/prwrapper/.env
    environment:
      NODE_ENV: development
    command: node dist/apps/prwrapper/src/main.js

  octokit:
    build:
      context: .
      dockerfile: ./apps/octokit/docker/dev.Dockerfile
      target: development
    ports:
      - '3200:3200'
    volumes:
      - .:/app
    env_file:
      - ./apps/octokit/.env
    environment:
      NODE_ENV: development
    command: node dist/apps/octokit/src/main.js
