services:
  api:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    command: pnpm run start:dev api