name: Build, Lint, and Test

on:
  push:
    branches:
      - main
      - feature-branch
  pull_request:
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: nx run-many --targets=build --all

      - name: Lint the project
        run: nx run-many --targets=lint --all

      - name: Run tests
        run: nx run-many --targets=test --all

      - name: Security audit
        run: pnpm audit
